# Generated by Django 3.2.9 on 2021-12-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование кружка')),
            ],
            options={
                'verbose_name': 'Кружок',
                'verbose_name_plural': 'Кружоки',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Дни кружка')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Платеж за месяц')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Учители')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учители',
            },
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя ученика')),
                ('lastname', models.CharField(max_length=150, verbose_name='Фамилия ученика')),
                ('age', models.IntegerField(default=0, verbose_name='Лет ученика')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.category', verbose_name='Кружок')),
                ('days', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.days', verbose_name='Дни кружок')),
                ('money', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.money', verbose_name='Ежемесячный платеж')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='edu.teacher', verbose_name='Учители')),
            ],
        ),
    ]
